---
regions:
  - name: region1
    display_name: region1

availability_zones:
  - name: az1
    display_name: az1

network_interface_groups:
  - name: interface_group1
    display_name: interface_group1
    availability_zone: az1
    region: region1
    group_type: eth
    mtu: 1500
    gateway: 172.17.1.1
    prefix: 172.17.1.0/24

storage_endpoints:
  - name: default
    display_name: default
    endpoint_type: iscsi
    address: ["172.17.1.2/24", "172.17.1.3/24"]
    gateway: 172.17.1.1
    network_interface_groups: ["interface_group1"]
    availability_zone: az1

arrays:
  - name: flasharray1
    display_name: flasharray1
    appliance_id: 1187351-242133817-5976825671211737520
    host_name: flasharray1
    hardware_type: flash-array-x
    az: az1
    region: region1
  - name: flasharray2
    display_name: flasharray2
    appliance_id: 4044399-202674005-8936155360115641845
    host_name: flasharray2
    hardware_type: flash-array-x
    az: az1
    region: region1
